### ISSUE TITLE
clearvoid causing rendering client crash 1.19.2

### ISSUE THREAD

**Issue by netcore10** [yezhiyi9670/clear-void#1]
https://paste.atlauncher.com/view/f9a7fe9a-d181-403e-b808-b50067a3e278

it was fixed the moment i removed the mod

**Comment by yezhiyi9670** [comment]
I also found earilier that the way of patching is breaking because the gl fragment for the dark sky is removed. The game crashed when I tried to turn on shaders.

I'll try to fix this soon.

**Comment by yezhiyi9670** [comment]
I tried another way to remove the black void and released [version 1.3.0](https://modrinth.com/mod/clear-void/version/1.3.0). Please try it, and close the issue if the problem is solved.

**Comment by netcore10** [comment]
Seems to work now, thanks for fixing it! I'll let you know if anything comes up.
