### ISSUE TITLE
[Suggestion] Adding this mod to curseforge.

### ISSUE THREAD

**Issue by murao-kun** [yezhiyi9670/clear-void#2]
I really wish to include this mod into my modpack. But it is outside of curseforge system.
I really suggest to upload the mod to curseforge too. Or give me permissions to do so.

**Comment by murao-kun** [comment]
Same with your other project - https://github.com/yezhiyi9670/occlusion-culling-fix-sodium
I can't open issue their, so I will add this one there too. Really need to have that one on 1.19.2 in curseforge sustem to include in the modpack I am making.

**Comment by yezhiyi9670** [comment]
I have just uploaded these mods. They are awaiting moderation now.

**Comment by murao-kun** [comment]
Thank you! You are the best!
